#!/usr/bin/env bash
# Hardens the NOPASSWD sudoers rule that ii-sddm-theme installs.
#
# THE PROBLEM
#   setup.sh creates /etc/sudoers.d/sddm-theme-$USER containing:
#       $USER ALL=(ALL) NOPASSWD: /home/$USER/.config/ii-sddm-theme/sddm-theme-apply.sh
#   and copies that script as the user, so it ends up user-writable. Any process
#   running as $USER can rewrite it and gain root without a password. The target
#   of a NOPASSWD rule must never be writable by the user it grants rights to.
#
# THE FIX
#   The *code* that runs as root moves to /usr/local/bin, owned by root. The
#   *data* it reads (Colors.qml, Settings.qml, generated by matugen) stays in the
#   user's home: matugen runs as the user and has to be able to write it. That is
#   inherent to the design and is not root escalation -- the most it allows is
#   influencing the QML the greeter draws, and the greeter runs as user 'sddm'.
#
# Idempotent. Run AFTER setup.sh:  sudo ./harden-ii-sddm.sh
set -euo pipefail

THEME="ii-sddm-theme"
REAL_USER="${SUDO_USER:-$USER}"
USER_HOME="$(getent passwd "$REAL_USER" | cut -d: -f6)"

SRC_DIR="$USER_HOME/.config/$THEME"
OLD_SCRIPT="$SRC_DIR/sddm-theme-apply.sh"
NEW_SCRIPT="/usr/local/bin/sddm-theme-apply.sh"
SUDOERS="/etc/sudoers.d/sddm-theme-$REAL_USER"
MATUGEN_CONF="$USER_HOME/.config/matugen/config.toml"

[ "$(id -u)" -eq 0 ] || { echo "Run with sudo." >&2; exit 1; }

# --- 1. Move the script to /usr/local/bin, owned by root ---
if [ -f "$OLD_SCRIPT" ]; then
    install -o root -g root -m 755 "$OLD_SCRIPT" "$NEW_SCRIPT"
    echo "[ok] copied to $NEW_SCRIPT (root:root 755)"
elif [ -f "$NEW_SCRIPT" ]; then
    echo "[skip] $NEW_SCRIPT already exists"
else
    echo "[ERROR] $OLD_SCRIPT not found -- did you run setup.sh?" >&2; exit 1
fi

# --- 2. Pin SCRIPT_DIR ---
# The original derives it from BASH_SOURCE; from /usr/local/bin that would point
# there and it would not find Colors.qml or ii-sddm.conf. Pin it to the data dir.
# The guard checks for the BASH_SOURCE line itself, not for comment text, so it
# stays correct regardless of the language this script is written in.
if grep -q 'SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE\[0\]}")" && pwd)"' "$NEW_SCRIPT"; then
    sed -i 's|SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE\[0\]}")" \&\& pwd)"|SCRIPT_DIR="$USER_HOME/.config/ii-sddm-theme"  # pinned: this script lives in /usr/local/bin|' "$NEW_SCRIPT"
    echo "[ok] SCRIPT_DIR pinned to the data directory"
elif grep -q 'SCRIPT_DIR="\$USER_HOME/.config/ii-sddm-theme"' "$NEW_SCRIPT"; then
    echo "[skip] SCRIPT_DIR was already pinned"
else
    echo "[ERROR] SCRIPT_DIR line not recognised -- check by hand" >&2; exit 1
fi

# --- 3. Sudoers pointing at the root-owned binary ---
tmp="$(mktemp)"
printf '%s ALL=(ALL) NOPASSWD: %s\n' "$REAL_USER" "$NEW_SCRIPT" > "$tmp"
if ! visudo -c -f "$tmp" >/dev/null 2>&1; then
    echo "[ERROR] invalid sudoers rule, nothing touched" >&2; rm -f "$tmp"; exit 1
fi
install -o root -g root -m 0440 "$tmp" "$SUDOERS"
rm -f "$tmp"
echo "[ok] $SUDOERS -> $NEW_SCRIPT"

# --- 4. Point matugen's post_hook at the new binary ---
if [ -f "$MATUGEN_CONF" ] && grep -q "\.config/$THEME/sddm-theme-apply\.sh" "$MATUGEN_CONF"; then
    cp "$MATUGEN_CONF" "$MATUGEN_CONF.bak-harden"
    sed -i "s|sudo [^ ]*\.config/$THEME/sddm-theme-apply\.sh|sudo $NEW_SCRIPT|g" "$MATUGEN_CONF"
    chown "$REAL_USER":"$REAL_USER" "$MATUGEN_CONF"
    echo "[ok] matugen post_hook updated (backup in config.toml.bak-harden)"
else
    echo "[skip] matugen does not reference the old path"
fi

# --- 5. Drop the old script so no stale copy remains ---
if [ -f "$OLD_SCRIPT" ]; then
    rm -f "$OLD_SCRIPT"
    echo "[ok] removed $OLD_SCRIPT (the .qml/.conf data stays)"
fi

echo
echo "=== Verification ==="
ls -l "$NEW_SCRIPT"
echo -n "sudoers: "; cat "$SUDOERS"
echo -n "writable by $REAL_USER? "
sudo -u "$REAL_USER" test -w "$NEW_SCRIPT" && echo "YES - BAD" || echo "no - correct"
